username = input("Введите имя")
title = input("Введите заголовок заметки")
content = input("Введите описание заметки")
status = input("Введите статус заметки")
created_date = input("Введите дату в формате Д-М-Г")
issue_date = input("Введите дату в формате Д-М-Г")